### PR TITLE
Update to master and add descriptor set mapping

### PR DESCRIPTION
**Pull request by msiglreith**
* Update to the latest SPIRV-Cross version, including fixes for HLSL y-axis inversion
* Add mapping of descriptor sets to register space for HLSL ShaderModel >= 5.1

### CODE REVIEW

**Comment by msiglreith** [comment]
(Rebase+merge recommended imo)

**Comment by grovesNL** [comment]
Do you plan to submit 68da681 upstream too?

**Comment by msiglreith** [comment]
Not now. I would like to keep it in this fork to see how it works out, if this is ok.

**Comment by grovesNL** [comment]
Sure, sounds good.

**Pull request merged**
